### ISSUE TITLE
VO has no Id

### ISSUE THREAD

**Issue by pigay** [quattor/scdb-ant-utils#2]
I'm trying to update VO config and I encounter the following error:

> Buildfile: build.xml
> 
> init:
> 
> define.tasks:
> 
> update.vo.config:
>         [echo] Updating VO parameters in /home/pigay/cdb/cfg/grid/*
> [quattor-voconfig] Retrieving configuration for VO aegis
> [quattor-voconfig] Error parsing VO ID cars
> (http://operations-portal.egi.eu/xml/voIDCard/public/all/true)
> 
> BUILD FAILED
> /home/pigay/cdb/quattor.build.xml:435: BUILD FAILED : Invalid
> configuration: VO has no Id

Seems to be a known issue (at least @Pansanel knows it)

**Comment by Pansanel** [comment]
I am currently in touch with Cyril regarding this issue. The CIC_ID tag has been removed from the VO ID Card. Only the Serial tag is available, but there is no link between CIC_ID and Serial. I have asked to Cyril to put the old tag back. I will also propose a fix which permit to use the Serial for generating UIDs and VO's username (a solution for a smooth transition).

**Comment by pigay** [comment]
I gave another try. It seems to be better, but it ends with the following exception:

```
[quattor-voconfig] VO configuration for VO lofar (ID=251):
[quattor-voconfig]     VOMS Server: null (VOMS port=30019, voms-admin=true)
[quattor-voconfig] Writing template for VO lofar (/home/pigay/cdb/cfg/grid/umd-3/vo/params/lofar.tpl)
[quattor-voconfig]     Suffix 'yzh' not unique for FQAN /surveys (attempt 1)
[quattor-voconfig] VO configuration for VO lsgrid (ID=1390):
[quattor-voconfig]     VOMS Server: null (VOMS port=30018, voms-admin=true)
[quattor-voconfig] Writing template for VO lsgrid (/home/pigay/cdb/cfg/grid/umd-3/vo/params/lsgrid.tpl)
[quattor-voconfig]     INFO: VO lsgrid has no specific FQAN defined
[quattor-voconfig] VO configuration for VO lsst (ID=10281):
[quattor-voconfig]     VOMS Server: null (VOMS port=15003, voms-admin=true)
[quattor-voconfig]     VOMS Server: null (VOMS port=15003, voms-admin=false)
[quattor-voconfig]     VOMS Server: null (VOMS port=15003, voms-admin=true)
[quattor-voconfig] Writing template for VO lsst (/home/pigay/cdb/cfg/grid/umd-3/vo/params/lsst.tpl)
[quattor-voconfig]     INFO: VO lsst has no specific FQAN defined
[quattor-voconfig] VO configuration for VO lz (ID=10320):
[quattor-voconfig]     VOMS Server: null (VOMS port=15002, voms-admin=true)
[quattor-voconfig] Writing template for VO lz (/home/pigay/cdb/cfg/grid/umd-3/vo/params/lz.tpl)

BUILD FAILED
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
    at java.lang.String.substring(String.java:1946)
    at org.quattor.ant.VOConfigTask$VOConfig.setAccountPrefix(VOConfigTask.java:641)
    at org.quattor.ant.VOConfigTask$VOConfig.getAccountPrefix(VOConfigTask.java:601)
    at org.quattor.ant.VOConfigTask$VOConfig.writeVOTemplate(VOConfigTask.java:700)
    at org.quattor.ant.VOConfigTask$VOConfig.access$000(VOConfigTask.java:562)
    at org.quattor.ant.VOConfigTask.execute(VOConfigTask.java:277)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:622)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:357)
    at org.apache.tools.ant.Target.performTasks(Target.java:385)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
    at org.apache.tools.ant.Main.runBuild(Main.java:758)
    at org.apache.tools.ant.Main.startAnt(Main.java:217)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)

Total time: 2 seconds
```

Maybe it's not related to the preceding?

**Comment by Pansanel** [comment]
This is a new issue! The VOConfig Task requires the VO name to be at least 3 characters long. A new VO has been added to the CIC file, called 'lz'.
I will do a fix for it. Meanwhile, you can download:
http://operations-portal.egi.eu/xml/voIDCard/public/all/true
remove then entry related to the 'lz' VO and place the file on a webserver.
Then update the link defined by the voConfigUri variable in your quattor.build.xml file to point to the new location!

**Comment by pigay** [comment]
Hi Jérôme,

The workaround works!

Incidentally, generated cert templates is sometimes incorrect. It contains lines like:

```
-----END CERTIFICATE-----EOF
```

which lacks a carriage return. I had to manually replace with:

```
-----END CERTIFICATE-----
EOF
```

I opened #4 for this specific bug.

Many thanks,

Pierre

**Comment by pigay** [comment]
Also, certificate for server voms1.egee.cesnet.cz is missing in generated template. Maybe others as well. Strange...

**Comment by Pansanel** [comment]
It is normal for voms1.egee.cesnet.cz. It has been replaced by voms1.grid.cesnet.cz. Probably that the entry has not been updated by the VO manager.

**Comment by pigay** [comment]
But voms1.egee.cesnet.cz certificate is present in the voIDCard xml. I read the following error in ant task, however:

```
[quattor-voconfig] Updating template for VOMS server voms1.egee.cesnet.cz (/home/pigay/cdb/cfg/grid/umd-3/vo/certs/voms1.egee.cesnet.cz.tpl)
[quattor-voconfig]     VOMS server voms1.egee.cesnet.cz has no certificate defined in VO ID card. Ignoring existing certificate.
```

Which leads to empty certificate in the quattor template. ncm-vomsclient will fail in turn on the quattor clients.

The same error appears for these servers:

```
[quattor-voconfig]     VOMS server caribe.uniandes.edu.co has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server grid.org.ua has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server ngi-il-voms1.isragrid.org.il has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server rdig-registrar.sinp.msu.ru has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms.cern.ch has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms.eela.ufrj.br has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms.grid.am has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms.grid.auth.gr has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms.grid.edges-grid.eu has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms.grid.ikd.kiev.ua has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms.hpcc.ttu.edu has no certificate defined in VO ID card. Ignoring existing certificate.
[quattor-voconfig]     VOMS server voms1.egee.cesnet.cz has no certificate defined in VO ID card. Ignoring existing certificate.
```
